### ISSUE TITLE
Plugin should clone retirement scripts from edx-platform, not from tubular

### ISSUE THREAD

**Issue by feanil** [hastexo/tutor-contrib-retirement#32]
Hey All,

I just wanted to inform the maintainers of this plugin about a change coming up to the retirement code.  It's moving from the tubular repo to the edx-platform repo as a part of  https://github.com/openedx/axim-engineering/issues/881

**Comment by fghaas** [comment]
Ah very nice, thanks @feanil! We much appreciate the heads-up.

**Comment by mrtmm** [comment]
Hi @feanil, what's the expectation for folks currently running on Quince (or older releases)? Will there be a backport of the retirement scripts to older releases? For this plugin, when moving away from the Tubular repository, it would make sense to then rely on on the `openedx` image we already build anyway that includes `edx-platform` and drop the custom image we build here now.

**Comment by mrtmm** [comment]
@feanil Ack, yes it does answer my question, thanks! I suppose we need to implement this change when we add support for the Redwood release and use it as it is for Quince.
