### ISSUE TITLE
Several retirement issues on Quince instance with Course Discovery enabled

### ISSUE THREAD

**Issue by dyudyunov** [hastexo/tutor-contrib-retirement#39]
# Summary

1. The issue with discovery retirement is located [here](https://github.com/openedx-unsupported/tubular/blob/open-release/quince.2/tubular/scripts/retire_one_learner.py#L193).
[Quick solution] Remove the Discovery step from the pipeline.
That's because the config is updated with services' APIs [here](https://github.com/openedx-unsupported/tubular/blob/open-release/quince.2/tubular/scripts/helpers.py#L143), but there is no Discovery service -> we are getting the key error when trying to get it from the config -> pipeline fails. In other words - tubular can't (and never could) handle Discovery retirement.
The same story for the [retirement scripts migrated to the edx-platform](https://github.com/openedx/edx-platform/blob/master/scripts/user_retirement/utils/helpers.py#L144).
[Better one] Update the retirement scripts in the edx-platform (tubular is dead) to support discovery retirement.
2. RETIRE_MAILINGS pipeline step should be removed from the plugin as well because it was deprecated and removed as a separate API endpoint from the LMS [starting from the Ironwood release](https://github.com/openedx/edx-platform/pull/19320/commits/9b3abd5598f4a7abc3760e4b724b2ce23506788f#diff-3c69166f3f19cc3b4fc216639c958740f56b6598c2e3a172cb036d7c055c0f2eL349) and now it is a part of the [LMS_MISC step](https://github.com/openedx/edx-platform/blob/3e090014f68f75bb291d9bb6c37960c294d27cf1/openedx/core/djangoapps/user_api/accounts/views.py#L1114).
3. Retirement steps order is different from retirement state indexes in the DB after migration. To avoid errors we need to place Enrollments retirement before the Forum retirement.

## What I did

I have a [working version](https://github.com/hastexo/tutor-contrib-retirement/compare/main...GSVlabs:tutor-contrib-philu-retirement:philu-main) that has already been tested on our instances.

Notes: 
- I also removed the Ecommerce-related steps from the RETIREMENT_STATES list because it is unneeded after the [recent PR has been merged](https://github.com/hastexo/tutor-contrib-retirement/pull/37).
- I applied the "Quick" solution for the Discovery issue which is not the best choice

## What I expected to happen

It would be great to apply fixes for the listed issues.

## My environment

Please add some information about the environment that you’re working in. At a minimum, include these items:

* Tutor version: v17.0.1
* `tutor-contrib-retirement` version: my fork is based on v3.3.1
* Output of the retirement command/CronJob: 

Discovery error:
```
Retiring tmp1
b'Learner Retirement: Starting learner retirement for tmp1 using config file ./pipeline_config/config.yml'
b'Learner Retirement: Starting state RETIRING_DISCOVERY'
b"Learner Retirement: Error in retirement state RETIRING_DISCOVERY: 'DISCOVERY'"
b'Learner Retirement: Error encountered in state "RETIRING_DISCOVERY"\n\'DISCOVERY\''
b'Learner Retirement: Traceback (most recent call last):\n  File "scripts/retire_one_learner.py", line 193, in retire_learner\n    response = getattr(config[service], method)(learner)\nKeyError: \'DISCOVERY\'\n'
```
For wrong pipeline steps order:
```
 Moved from FORUMS_COMPLETE (step 81) to ERRORED (step 131):
400 Client Error: Bad Request for url: https://lms-philantrophy-dev.raccoongang.net/api/user/v1/accounts/update_retirement_status/
```

**Comment by fghaas** [comment]
@dyudyunov Sorry for the slow response here; annual leave got in the way. I've taken the changes from your topic branch, broken them into 4 commits instead of 2, updated some of the commit messages, and added updates to the documentation. See PR #40.

**Comment by dyudyunov** [comment]
> @dyudyunov Sorry for the slow response here; annual leave got in the way. I've taken the changes from your topic branch, broken them into 4 commits instead of 2, updated some of the commit messages, and added updates to the documentation. See PR #40.

Thank you!
